---
  - name: "show remote environment"
    shell: env

  - name: "copy backend binaries"
    become: yes
    copy:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app

  - name: "copy node_modules"
    become: yes
    copy:
      src: ../../backend/node_modules
      dest: /home/ubuntu/uda_app

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/uda_app/dist
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./src/migrations"
     TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
     TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

