---
  - name: "show remote environment"
    shell: env

  - name: Copy compiled files
    ansible.builtin.copy:
      src: /tmp/workspace/backend.tar.gz 
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode: 0755

  - name: Copy backend
    become: yes
    shell: |
      cd /home/ubuntu
      tar -xvf /home/ubuntu/backend.tar.gz

  - name: "Build and Start application"
    become: yes
    shell: |
      cd /home/ubuntu/backend
      npm install
      pm2 stop default
      pm2 start npm -- start
      pm2 ls

