---
  - name: "show remote environment"
    shell: env

  - name: Copy compiled files
    ansible.builtin.copy:
      src: /root/project/artifact.tar.gz 
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode: 0755

  - name: Copy backend
    become: yes
    shell: |
      cd /home/ubuntu
      mkdir backend
      cd backend
      tar -xvf /home/ubuntu/artifact.tar.gz

  - name: "Build and Start application"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 ls

