---
  - name: "show remote environment"
    shell: env

  - name: Create app dir
    become: yes
    file:
      path: /home/ubuntu/app
      state: directory

  - name: "Copy backend build folder to EC2"
    become: yes
    unarchive:
      src: /tmp/workspace/backend.tar.gz
      dest: /home/ubuntu/app/
      owner: ubuntu

  - name: "Copy package.json to EC2"
    become: yes
    copy:
      src: /tmp/workspace/package.json
      dest: /home/ubuntu/app/
      owner: ubuntu

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: Start server
    become: true
    shell: |
      cd /home/ubuntu/app
      pm2 start npm --name backend -- start
      pm2 ls
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./src/migrations"
      TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
      TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

